const nationalities = [
  { name: "thai", label: "ไทย" },
  { name: "afghan", label: "Afghan" },
  { name: "albanian", label: "Albanian" },
  { name: "algerian", label: "Algerian" },
  { name: "american", label: "American" },
  { name: "andorran", label: "Andorran" },
  { name: "angolan", label: "Angolan" },
  { name: "antiguans", label: "Antiguans" },
  { name: "argentinean", label: "Argentinean" },
  { name: "armenian", label: "Armenian" },
  { name: "australian", label: "Australian" },
  { name: "austrian", label: "Austrian" },
  { name: "azerbaijani", label: "Azerbaijani" },
  { name: "bahamian", label: "Bahamian" },
  { name: "bahraini", label: "Bahraini" },
  { name: "bangladeshi", label: "Bangladeshi" },
  { name: "barbadian", label: "Barbadian" },
  { name: "barbudans", label: "Barbudans" },
  { name: "batswana", label: "Batswana" },
  { name: "belarusian", label: "Belarusian" },
  { name: "belgian", label: "Belgian" },
  { name: "belizean", label: "Belizean" },
  { name: "beninese", label: "Beninese" },
  { name: "bhutanese", label: "Bhutanese" },
  { name: "bolivian", label: "Bolivian" },
  { name: "bosnian", label: "Bosnian" },
  { name: "brazilian", label: "Brazilian" },
  { name: "british", label: "British" },
  { name: "bruneian", label: "Bruneian" },
  { name: "bulgarian", label: "Bulgarian" },
  { name: "burkinabe", label: "Burkinabe" },
  { name: "burmese", label: "Burmese" },
  { name: "burundian", label: "Burundian" },
  { name: "cambodian", label: "Cambodian" },
  { name: "cameroonian", label: "Cameroonian" },
  { name: "canadian", label: "Canadian" },
  { name: "cape verdean", label: "Cape Verdean" },
  { name: "central african", label: "Central African" },
  { name: "chadian", label: "Chadian" },
  { name: "chilean", label: "Chilean" },
  { name: "chinese", label: "Chinese" },
  { name: "colombian", label: "Colombian" },
  { name: "comoran", label: "Comoran" },
  { name: "congolese", label: "Congolese" },
  { name: "costa rican", label: "Costa Rican" },
  { name: "croatian", label: "Croatian" },
  { name: "cuban", label: "Cuban" },
  { name: "cypriot", label: "Cypriot" },
  { name: "czech", label: "Czech" },
  { name: "danish", label: "Danish" },
  { name: "djibouti", label: "Djibouti" },
  { name: "dominican", label: "Dominican" },
  { name: "dutch", label: "Dutch" },
  { name: "east timorese", label: "East Timorese" },
  { name: "ecuadorean", label: "Ecuadorean" },
  { name: "egyptian", label: "Egyptian" },
  { name: "emirian", label: "Emirian" },
  { name: "equatorial guinean", label: "Equatorial Guinean" },
  { name: "eritrean", label: "Eritrean" },
  { name: "estonian", label: "Estonian" },
  { name: "ethiopian", label: "Ethiopian" },
  { name: "fijian", label: "Fijian" },
  { name: "filipino", label: "Filipino" },
  { name: "finnish", label: "Finnish" },
  { name: "french", label: "French" },
  { name: "gabonese", label: "Gabonese" },
  { name: "gambian", label: "Gambian" },
  { name: "georgian", label: "Georgian" },
  { name: "german", label: "German" },
  { name: "ghanaian", label: "Ghanaian" },
  { name: "greek", label: "Greek" },
  { name: "grenadian", label: "Grenadian" },
  { name: "guatemalan", label: "Guatemalan" },
  { name: "guinea-bissauan", label: "Guinea-Bissauan" },
  { name: "guinean", label: "Guinean" },
  { name: "guyanese", label: "Guyanese" },
  { name: "haitian", label: "Haitian" },
  { name: "herzegovinian", label: "Herzegovinian" },
  { name: "honduran", label: "Honduran" },
  { name: "hungarian", label: "Hungarian" },
  { name: "icelander", label: "Icelander" },
  { name: "indian", label: "Indian" },
  { name: "indonesian", label: "Indonesian" },
  { name: "iranian", label: "Iranian" },
  { name: "iraqi", label: "Iraqi" },
  { name: "irish", label: "Irish" },
  { name: "israeli", label: "Israeli" },
  { name: "italian", label: "Italian" },
  { name: "ivorian", label: "Ivorian" },
  { name: "jamaican", label: "Jamaican" },
  { name: "japanese", label: "Japanese" },
  { name: "jordanian", label: "Jordanian" },
  { name: "kazakhstani", label: "Kazakhstani" },
  { name: "kenyan", label: "Kenyan" },
  { name: "kittian and nevisian", label: "Kittian and Nevisian" },
  { name: "kuwaiti", label: "Kuwaiti" },
  { name: "kyrgyz", label: "Kyrgyz" },
  { name: "laotian", label: "Laotian" },
  { name: "latvian", label: "Latvian" },
  { name: "lebanese", label: "Lebanese" },
  { name: "liberian", label: "Liberian" },
  { name: "libyan", label: "Libyan" },
  { name: "liechtensteiner", label: "Liechtensteiner" },
  { name: "lithuanian", label: "Lithuanian" },
  { name: "luxembourger", label: "Luxembourger" },
  { name: "macedonian", label: "Macedonian" },
  { name: "malagasy", label: "Malagasy" },
  { name: "malawian", label: "Malawian" },
  { name: "malaysian", label: "Malaysian" },
  { name: "maldivan", label: "Maldivan" },
  { name: "malian", label: "Malian" },
  { name: "maltese", label: "Maltese" },
  { name: "marshallese", label: "Marshallese" },
  { name: "mauritanian", label: "Mauritanian" },
  { name: "mauritian", label: "Mauritian" },
  { name: "mexican", label: "Mexican" },
  { name: "micronesian", label: "Micronesian" },
  { name: "moldovan", label: "Moldovan" },
  { name: "monacan", label: "Monacan" },
  { name: "mongolian", label: "Mongolian" },
  { name: "moroccan", label: "Moroccan" },
  { name: "mosotho", label: "Mosotho" },
  { name: "motswana", label: "Motswana" },
  { name: "mozambican", label: "Mozambican" },
  { name: "namibian", label: "Namibian" },
  { name: "nauruan", label: "Nauruan" },
  { name: "nepalese", label: "Nepalese" },
  { name: "new zealander", label: "New Zealander" },
  { name: "ni-vanuatu", label: "Ni-Vanuatu" },
  { name: "nicaraguan", label: "Nicaraguan" },
  { name: "nigerien", label: "Nigerien" },
  { name: "north korean", label: "North Korean" },
  { name: "northern irish", label: "Northern Irish" },
  { name: "norwegian", label: "Norwegian" },
  { name: "omani", label: "Omani" },
  { name: "pakistani", label: "Pakistani" },
  { name: "palauan", label: "Palauan" },
  { name: "panamanian", label: "Panamanian" },
  { name: "papua new guinean", label: "Papua New Guinean" },
  { name: "paraguayan", label: "Paraguayan" },
  { name: "peruvian", label: "Peruvian" },
  { name: "polish", label: "Polish" },
  { name: "portuguese", label: "Portuguese" },
  { name: "qatari", label: "Qatari" },
  { name: "romanian", label: "Romanian" },
  { name: "russian", label: "Russian" },
  { name: "rwandan", label: "Rwandan" },
  { name: "saint lucian", label: "Saint Lucian" },
  { name: "salvadoran", label: "Salvadoran" },
  { name: "samoan", label: "Samoan" },
  { name: "san marinese", label: "San Marinese" },
  { name: "sao tomean", label: "Sao Tomean" },
  { name: "saudi", label: "Saudi" },
  { name: "scottish", label: "Scottish" },
  { name: "senegalese", label: "Senegalese" },
  { name: "serbian", label: "Serbian" },
  { name: "seychellois", label: "Seychellois" },
  { name: "sierra leonean", label: "Sierra Leonean" },
  { name: "singaporean", label: "Singaporean" },
  { name: "slovakian", label: "Slovakian" },
  { name: "slovenian", label: "Slovenian" },
  { name: "solomon islander", label: "Solomon Islander" },
  { name: "somali", label: "Somali" },
  { name: "south african", label: "South African" },
  { name: "south korean", label: "South Korean" },
  { name: "spanish", label: "Spanish" },
  { name: "sri lankan", label: "Sri Lankan" },
  { name: "sudanese", label: "Sudanese" },
  { name: "surinamer", label: "Surinamer" },
  { name: "swazi", label: "Swazi" },
  { name: "swedish", label: "Swedish" },
  { name: "swiss", label: "Swiss" },
  { name: "syrian", label: "Syrian" },
  { name: "taiwanese", label: "Taiwanese" },
  { name: "tajik", label: "Tajik" },
  { name: "tanzanian", label: "Tanzanian" },
  { name: "togolese", label: "Togolese" },
  { name: "tongan", label: "Tongan" },
  { name: "trinidadian or tobagonian", label: "Trinidadian or Tobagonian" },
  { name: "tunisian", label: "Tunisian" },
  { name: "turkish", label: "Turkish" },
  { name: "tuvaluan", label: "Tuvaluan" },
  { name: "ugandan", label: "Ugandan" },
  { name: "ukrainian", label: "Ukrainian" },
  { name: "uruguayan", label: "Uruguayan" },
  { name: "uzbekistani", label: "Uzbekistani" },
  { name: "venezuelan", label: "Venezuelan" },
  { name: "vietnamese", label: "Vietnamese" },
  { name: "welsh", label: "Welsh" },
  { name: "yemenite", label: "Yemenite" },
  { name: "zambian", label: "Zambian" },
  { name: "zimbabwean", label: "Zimbabwean" },
];
export default nationalities;
