export const FETCH_GENERIC_NATIONALITIES = "generic/FETCH_NATIONALITIES";
export const GENERIC_SET_NATIONALITIES = "generic/SET_NATIONALITIES";
export const FETCH_GENERIC_SEXES = "generic/FETCH_SEXES";
export const GENERIC_SET_SEXES = "generic/SET_SEXES";
