export const FETCH_GENERIC_NATIONALITIES = "generic/FETCH_NATIONALITIES";
export const SET_GENERIC_NATIONALITIES = "generic/SET_NATIONALITIES";
export const FETCH_GENERIC_SEXES = "generic/FETCH_SEXES";
export const SET_GENERIC_SEXES = "generic/SET_SEXES";
export const SEARCH_GENERIC_DESTINATIONS = "generic/SEARCH_DESTINATIONS";
export const SET_GENERIC_DESTINATIONS = "generic/SET_DESTINATIONS";
export const FETCH_GENERIC_TRANSPORTATION = "generic/FETCH_TRANSPORTATION";
export const SET_GENERIC_TRANSPORTATION = "generic/SET_TRANSPORTATION";
export const SET_GENERIC_GLOBAL_SNACKBAR_CONFIGS =
  "generic/SET_GLOBAL_SNACKBAR_CONFIGS";
