export const GET_TRANSACTION_NUMBER = "transaction/GET_TRANSACTION_NUMBER";
export const FETCH_TRANSACTION_AVAILABLE_TOUR_GUIDES =
  "transaction/FETCH_TRANSACTION_AVAILABLE_TOUR_GUIDES";
export const TRANSACTION_CHECKOUT = "transaction/CHECKOUT";
export const FETCH_TRANSACTIONS = "transaction/FETCH";
